# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214ca986bf37930fe3d034c0f06a3827b59f4254f140d8ead53b0e514b539d3b00135f12f0a56100aee3fe26ade02cfebbad7accb6bf47e21d3b458459d8b18e

test:
  secret_key_base: 3323adaf262f96ab79919f50aad9bb0edd6018acbfe8430bbf9fa4be148c706cb985af61e6fc1f619d57a54588763d148089aeb9b5b57881bd65b7d8c33525ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
